### ISSUE TITLE
마이페이지

### ISSUE THREAD

**Issue by calla1102** [SMUMC-7th/Team-B-FE#6]
### 필요기능

**프로필**
   - 성별에 따라 이미지 선정
   - 닉네임에 이름 불러오기
  
**메인화면**
   -닉네임 변경 버튼 -> 화면 전환도 _(내가)_
   -비밀번호 변경 버튼 -> 화면 전환도 _(지현언니가)_
   -알림설정 -> 화면 전환도 _(담당 미정)_

### **TODO list**
- [x] 마이페이지 기본 화면 구현
   - [x] 성별에 따라 프로필 이미지 바뀜
   
- [x] "닉네임 변경" 버튼 누르면 변경 페이지로 전환
- [x] 닉네임 입력 후 "변경 완료" 버튼 누르면 mypage화면 닉네임 변환
