### ISSUE TITLE
회원가입

### ISSUE THREAD

**Issue by calla1102** [SMUMC-7th/Team-B-FE#8]
### 필요기능

**step1**
   -이메일, 비밀번호 입력
   - "중복된 이메일입니다." 멘트 떠야함
   - 이메일 인증번호 받는 화면 필요
   - 인증번호에서 "완료"누르면 step2로 화면전환
  
**step2**
   -이름, 닉네임 입력
   -성별 선택
   -성별 선택 후 step3로 화면 전환

**step3**
   -배경 애니메이션 추가
   -클로디 이미지 삽입
   -로그인 버튼

### **TODO list**
**STEP1**
- [x] circle이 step1에 있도록
- [x] 이메일 입력 view
- [x] 비밀번호 입력 view
- [x] "중복된 이메일입니다" -> gone처리
- [x] 이메일 인증 번호 입력
- [x] 완료 후 화면 전환
   
**STEP2**
- [x] circle이 step2에 있도록
- [x] 이름 입력 view
- [x] 닉네임 입력 view
- [x] 성별 선택
- [x] 완료 후 화면 전환

**STEP3**
- [x] circle이 step3에 있도록
- [x] 배경색 애니메이션 구현
- [x] 가입완료 멘트
- [x] 로그인 버튼
- [x] 완료 후 화면 전환
